name: nation_test
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  dio: ^4.0.4
  freezed_annotation: ^1.1.0
  retrofit: ">=3.0.0 <4.0.0"
  flutter_bloc: ^8.0.1
  bloc: ^8.0.3
  go_router: ^3.0.4
  get_it: ^7.2.0
  injectable: ^1.5.3
  bloc_concurrency: ^0.2.0
  json_annotation: ^4.4.0
  curl_logger_dio_interceptor: ^0.0.2
  percent_indicator: ^4.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  lint: ^1.8.2
  flutter_lints: ^1.0.4
  build_runner: ^2.1.8
  args: ^2.1.1
  freezed: ^1.1.1
  retrofit_generator: ^4.0.1
  json_serializable: ^6.1.5
  injectable_generator: ^1.5.3
  http_mock_adapter: ^0.3.2
  mockito: ^5.1.0
  page_object: ^0.2.0

flutter:
  uses-material-design: true

flutter_intl:
  enabled: true
  main_locale: en